README.md
reactive/docker.py

This PR installs docker-compose in the recommended method from docker documents.

Docker compose

---

wheelhouse.txt

Adds VCVersioner to wheelhouse

---

wheelhouse.txt

This reverts commit c214a7990c841f67da71be86545d7458c1b0b6d1.

Revert "pin docker-py"

---

Makefile
tox.ini

Adds tactics to the linter. Updates the virtualenv in tox to python 3.4

Tox updates to support tactics linting

---

reactive/docker.py
scripts/install_docker.sh

dpkg configuration force conf, render docker-opts after install

---

scripts/install_docker.sh

Hotfix for https://github.com/juju-solutions/layer-docker/issues/21

Fix missing custom Docker daemon options in systemd

---

metadata.yaml

Related to https://github.com/juju/charm-tools/issues/186 where my short name was used in this layer.
I realized that the summary and description had old terminology so I updated them with different words.

Elminiate old terminology and update maintainer.

---

metadata.yaml

Removed series from metadata

---

.drone.yml
.travis.yml

We are now using travis to automatically lint and run the tests for this repo.

Replacing drone with travis for automated testing.

---

README.md

Addressing review comments from a previous pr.

Addressing review comments.

---

reactive/docker.py

Add workload daemon detection gate before allowing

---

layer.yaml
metadata.yaml
reactive/docker.py

Also changed the `docker.restart` functionality slightly.

Adding the SDN bits to the docker layer.

---

reactive/docker.py

Updates for the messages and more logging.

Updating the status and log messages for this layer.

---

reactive/docker.py
tests/10-deploy.py

Race conditions everywhere when you dont guard your config.changed
events and wind up calling template logic way before you have your
binaries placed.

Adds decorator to halt config.changed events from running until docker.ready

---

layer.yaml
reactive/docker.py

this adds a dockerhost interface (well the interface layer for it) which is needed for things like datadog, etc

Add support for dockerhost

---

README.md

Correct https://github.com/juju-solutions/layer-docker URL.

Correct github docker-layer url

---

README.md
config.yaml
reactive/docker.py
templates/docker.systemd

Fixes juju-solutions/bundle-canonical-kubernetes#162

Add a "no_proxy" config option

---

README.md
config.yaml
layer.yaml
metadata.yaml
reactive/docker.py

Related to https://github.com/juju-solutions/bundle-canonical-kubernetes/issues/165

add an nrpe-external-master relation, and the related config options

---

copyright

Remove BSD-4 license in favor of ASL 2.0
Closes #102

Adds ASL 2.0 as license

---

reactive/docker.py

Needed to rename the states to avoid collision with the
kubernetes-master / kubernetes-worker layers.

add handling of nrpe-external-master relation departure

---

reactive/docker.py

Holds on upgrade or initial install.

Holding docker revision via apt-mark hold

---

config.yaml

This came up during testing the docker changes.

Set default value to auto for docker_runtime

---

config.yaml
templates/docker.defaults

https://github.com/juju-solutions/bundle-canonical-kubernetes/issues/726

Pinning `nvidia-docker2` package

---

actions.yaml
actions/upgrade-docker
lib/charms/layer/docker.py
reactive/docker.py

~~**DON'T MERGE BEFORE DISCUSSION.**~~
I've moved some functions around so they can be shared with the run action easily, this works with just deploying the layer, but we should test with some consumers (i.e. kubernetes-worker).

Adding a run-action to upgrade Docker
