juju-solutions/layer-docker

- .drone.yml
- .gitignore
- README.md
- actions.yaml
- actions/clean-containers
- actions/clean-images
- copyright
- icon.svg
- lib/dockeropts.py
- metadata.yaml
- tox.ini
- unit_tests/test_dockeropts.py
Adds a port of whitmo's DockerOpts manager (originally for ansible) to be used in Docker Charms deriving from the layer-docker layer. Use case is to easily manage flags from other layers/interfaces.
Consider the example of adding swarm. There are several options to add - changing how the daemon is launched with -H tcp://0.0.0.0:2456 (enabling a TCP service), and --label=swarm --label=manager. While we can template these, another layer adding an SDN plugin can clobber these changes, and exchanging this data over a "local" or "cluster" relation can be a bit clunky.
Having an exposed layer to keep it all localized, with a central unit repository for the data (Backed by charmhelpers.core.kvdata) that is persistent as new layers are mixed in and altering the defaults, this yields a single …
> Dockeropts manager

- config.yaml
- reactive/docker.py
- scripts/enable_grub_cgroups.sh
This causes a machine reboot on first run. It only recycles the host
to complete the memory accounting modules.
Updates #15 and #16
> Adds an option to tune the cgroup settings. Disabled by default

- .gitignore
- lib/charms/docker/__init__.py
- lib/charms/docker/compose.py
- lib/charms/docker/workspace.py
- reactive/docker.py
- tox.ini
- unit_tests/test_docker.py
- unit_tests/test_docker_compose.py
- unit_tests/test_docker_workspace.py
Includes service wrappers for Docker, DockerCompose
This is a breakout of lib concerns for the Docker charm base, which includes
a CLI compatible wrapper for executing docker commands in given contexts.
This is all convenience for the charm author - instead of littering
subprocess.check_call or subprocess.check_output methods in their hook
code. This abstraction allows for a clean API to perform common tasks.
Example Usage - use the bootstrap docker daemon to start flannel:
from charms.docker import Docker
d = Docker(socket="unix:///var/run/docker-bootstrap.sock")
if d.running():
d.run('quay.io/flannel/flannel', ports="4001:4001")
hookenv.open_port(4001)
Example Usage for DockerCompose - spin up nginx out of a composer formation
from charms.docker.compose import Compose
c = …
> Service wrappers

- layer.yaml
- reactive/docker.py
This is useful when building layer-docker based subordinates. The charm
has a self-relationship that is capable of denoting we are connecting
to an already juju maintained version of docker on the host. Why sit
through the implicit 40 sconds of probing when we can skip and get
directly to the workload.
Default behavior is to run the install hook though.
> Adds the skip_install layer option

- README.md
- layer.yaml
- reactive/docker.py
- wheelhouse.txt
Docker-compose has been pulled from the upstream docker ppa, which was weird, as it existed for a couple weeks. Regardless, installing from PIP on the production system is iffy. I think installing from the wheelhouse and keeping docker-compose encapsulated in the charm is the best path forward for now.
This commit also rolls up a few cleanup operations around the charm such as updating the readme, and adding a repo key to layer.yaml
> Encapsulate docker-compose in the wheelhouse

- README.md
Replacing dead link and adding more information on the build process of the layers.
> Fixing dead link and adding more description about the build

- wheelhouse.txt
Now that we are installing docker-compose in the wheelhouse, there's an
issue with its linking against dockerpy, which is fighting with the
setuptools in the wheelhouse/venv (i'm not sure which/how/etc.)
This is related to docker/docker-py#1019
> pin docker-py

- layer.yaml
- tactics/docker.py
- wheelhouse.txt
This adds a custom build tactic largely recommended by coryfu, however, it needs additional work to be a clean solution.
This requires some refactoring in charm-tools to clean up the wheelhouse tactic, and split into a few different methods so this becomes a 3 line tactic.
For now though, this unblocks all work with layer-docker and allows us to continue including upstream dependencies
> Once and for all deal with dockerpy's brokenness

- reactive/docker.py
Removing the hook decorator in favor of reactive states. This necessitates cleanliness for flake8
> Cleanup for flake8

- reactive/docker.py
I failed to realize that check_output returned a binary text stream which renders as b'amd64' when I was expecting 'amd64' and that messed up the deb line in the code.
> binary text streams in python3 will be the death of me.

- tests/00-setup
- tests/10-deploy.py
I ran these tests on a docker unit deployed to AWS and it worked.
```
$ ./10-deploy.py 
/usr/lib/python3/dist-packages/path.py:1719: DeprecationWarning: path is deprecated. Use Path instead.
warnings.warn(msg, DeprecationWarning)
2016-07-12 16:22:48 Starting deployment of local.amazon:testing1
2016-07-12 16:22:50 Deploying services...
2016-07-12 16:22:58 Adding relations...
2016-07-12 16:22:59 Deployment complete in 11.50 seconds
Docker version 1.11.2, build b9f10c9
Containers: 0
Running: 0
Paused: 0
Stopped: 0
Images: 0
Server Version: 1.11.2
Storage Driver: devicemapper
Pool Name: docker-202:1-264037-pool
Pool Blocksize: 65.54 kB
Base Device Size: 10.74 GB
Backing Filesystem: ext4
Data file: /dev/loop0
Metadata file: /dev/loop1
Data Space Used: 305.7 MB
Data Space Total: 107.4 GB
Data …
```
> Adding tests for the docker layer.

- wheelhouse.txt
layer-docker makes heavy use of templating in many situations. We should include the jinja2 render method by default to keep our subsidiary layers DRY
> Add charms.templating.jinja2 to wheelhouse

- exec.d/docker-compose/charm-pre-install
This is a temporary patch for #64, which i believe is fixed when we pack
all this in the wheelhouse.
> Upgrade pip due to the failure emitted from upstream docker libs

- config.yaml
- reactive/docker.py
Until this commit, layer-docker defaulted to installing from the docker
ppa. Docker 1.12 introduces a lot of interesting behavior changes behind
the scenes that can be problematic. Until we have a better pinning story
with this layer, I feel that this is the best path forward.
This will give our users the choice of which "distribution" of docker
they wish to install, and gives us the capacity to ensure we're building
against the work being put forth in the ubuntu archive. (read:
deployment into lxd containers with the docker profile)
> Defaults to archive

- LAYER_README.md
- README.md
- layer.yaml
The current README.md file was layer specific, so I moved that to LAYER_README.md and excluded it in the layer.yaml.
Created a README.md when we build the layer-docker into a charm.
> Renamed the layer readme, added a charm readme, exclude LAYER_README.md

- templates/docker.systemd
The recommended daemons switch between upstream packaging and the
docker.io package. This switch should help keep them in alignment when
deploying on the respective series
> Adds a missing template switch for daemons

- reactive/docker.py
Somewhere along the line we lost the capacity to toggle between upstream and installation from universe. This small bit of code corrects an immutable configuration option.
> Amend the immutable config

- reactive/docker.py
Docker was being stopped which gave the layer the apperance of not working.
This is problematic as when docker.available is raised, the daemon is
expected to be online and in a somewhat stable capacity.
This should restore user expectations
> Moved stop_service logic into a guarded if condition.

- reactive/docker.py
Wild guess fix for https://github.com/juju-solutions/bundle-canonical-kubernetes/issues/86. I'm guessing based on [this](https://github.com/juju-solutions/layer-docker/blob/f1bfadf304eb423325e6384e285e50f6c46f7489/reactive/docker.py#L83) and [this](https://github.com/juju-solutions/layer-docker/blob/f1bfadf304eb423325e6384e285e50f6c46f7489/reactive/docker.py#L225) that we just had the wrong state here. Any idea? @chuckbutler @mbruzek
> wild guess fix for proxy_changed step

- reactive/docker.py
In the current code in master, the docker daemon is left in a broken
state if the SDN provider ever goes away.
- renames the private method _reconfigure_docker_for_sdn to a much
clearer indication of whats happening
- Adds state detection to determine when we should stop workloads and
reconfigure the daemon
- Leverages the new methods added to the DockerOptsManager in
charms.docker 1.11.0 for popping flags out of the dict.
> Cleanup when sdn-plugin provider has gone away

- config.yaml
This adds defaults of empty string instead of None/Null types which
causes interesting side-effect behavior when using the 'config.changed'
states provided by layer-basic.
This is a work-around for
https://github.com/juju-solutions/layer-basic/issues/79 manifesting in
layer-docker.
> Work around the 'config.changed' states firing always

- debug-scripts/docker
- layer.yaml
This adds the `debug` action to layer-docker, along with a debug script to gather docker info. See [layer-debug](https://github.com/charms/layer-debug) for more info.
Additional discussion, where we decided this belongs in layer-docker, is here: https://github.com/juju-solutions/kubernetes/pull/81
@chuckbutler @mbruzek @wwwtyro
> Add debug script to layer-docker

- config.yaml
- layer.yaml
- metadata.yaml
Instead of specifying the nrpe-related config options and relations in
all the charms, it's better to use the nagios layer.
> migrate to the nagios layer

- debug-scripts/docker
This updates the debug script to grab docker logs and include them in the dump.
Follow-up to a Kubernetes debug session where container logs were absent and it would've helped us to see them.
> Add container logs to debug script

- metadata.yaml
This layer needed the series tag added to the metadata.yaml in
order to build independantly.
> Added series to metadata.yaml

- config.yaml
- reactive/docker.py
no_proxy config is passed to the docker.service file. If a line in docker.service file is greater than 2048 docker will not start properly (try it now, `juju config kubernetes-worker no_proxy=".....something long...."` and then `systemctl status docker.service` on a worker).
With this PR the charm will go into an error state until you give it a properly sized no_proxy. 
Should mitigate https://github.com/juju-solutions/bundle-canonical-kubernetes/issues/473
> Error when no_proxy is too long

- README.md
- config.yaml
- reactive/docker.py
- wheelhouse.txt
Moving the cuda-driver installation inside this layer simplifies things a lot. We do not need to care about loading and unloading kernel modules.
The nvidia docker we deploy is pinned to a specific version. The reason is I go the following error today:
```
The following packages have unmet dependencies:
 nvidia-docker2 : Depends: docker-ce (= 17.12.1~ce-0~ubuntu) but 18.03.0~ce-0~ubuntu is to be installed or
                           docker-ee (= 17.12.1~ee-0~ubuntu) but it is not installable
E: Unable to correct problems, you have held broken packages.
```
Already reported in https://github.com/NVIDIA/nvidia-docker/issues/643
This has happen in the past: https://github.com/NVIDIA/nvidia-docker/issues/540
So I would rather be safe and pin the versions I know they work and offer the …
> Move nvidia management in this layer

- tox.ini
Recent builds started failing with `no such option: --use-wheel`. Seems that --use-wheel is deprecated since pip 7 and remove in pip 9. We could have the option of `--only-binary :all:` but I do not think we need to be that strict.
This will unblock the build.
> Remove deprecated --use-wheel

- config.yaml
- layer.yaml
- reactive/docker.py
Default the key server to `hkp://keyserver.ubuntu.com:80`, but let users configure as needed.  On config changed, re-install docker via `toggle_docker_daemon_source()`.
Threw in a couple lint fixes for funzies.
> make apt key server configurable (fixes #120)

- config.yaml
- reactive/docker.py
We update the default values for cuda 10.0.130-1 and the nvidia docker stack. For the nvidia docker stack we removed the version pins as the package dependencies in bionic seem to be correct.
We also install the nvidia docker repo key from the `https://nvidia.github.io/nvidia-docker/gpgkey` as suggested in the official docs. This way we will not need to search for a new key fingerprint and re-release next time this key expires.
Fixes: https://github.com/juju-solutions/bundle-canonical-kubernetes/issues/664
> Move to latest cuda and remove version pins of nvidia docker stack

- config.yaml
Particularly, fix the unwieldy wording in no_proxy and remove references to routing in http{,s}_proxy.
> Improve grammar, spelling, punctuation

- config.yaml
- reactive/docker.py
Tested with `juju deploy ./builds/docker --config docker_runtime=custom --config docker_runtime_repo="deb [arch={ARCH}] https://download.docker.com/linux/ubuntu {CODE} stable" --config docker_runtime_key_url="https://download.docker.com/linux/ubuntu/gpg" --config docker_runtime_package=docker-ce`
```
$ docker version
Client:
Version:           18.09.0
API version:       1.39
Go version:        go1.10.4
Git commit:        4d60db4
Built:             Wed Nov  7 00:48:57 2018
OS/Arch:           linux/amd64
Experimental:      false
Server: Docker Engine - Community
Engine:
Version:          18.09.0
API version:      1.39 (minimum version 1.12)
Go version:       go1.10.4
Git commit:       4d60db4
Built:            Wed Nov  7 00:16:44 2018
OS/Arch:          linux/amd64
Experimental:     false …
```
> Ability to configure custom Docker repository

- config.yaml
Pinning version of `docker-ce` to fix dependency issue with `nvidia-docker2`.
> Pinning docker-ce version for Nvidia deployments

- config.yaml
Fixing the same nvidia packaging issue.
> Pinning nvidia-container-runtime version

- reactive/docker.py
If 'http_proxy' is available, apt-key command should utilize the
supplied proxy parameter.
Signed-off-by: Junaid Ali <junaidali.yahya@gmail.com>
> Using proxy while adding an apt-key

- lib/charms/layer/docker.py
This to fix a regression form the last change . 
Any docker-opts in the kubernetes worker charm was ignored .
Most common usage is usage of insecure registry
> Fix bug from this change ( Adding a run-action to upgrade Docker #135 )
